<a href="https://colab.research.google.com/github/bgsilva/curso-prog-python-09-2021/blob/main/Curso_IntroProgPy_BrunoSilva_2021_Aula3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução à Lógica de Programação
## Prof. Bruno Silva

## Aula 3: Coleções

* Listas 
* Tuplas
* Dicionários 
* *Arrays*

### 03/09/2021

# Listas

Listas são um tipo de variável que permite o armazenamento de vários valores,
acessados por um índice. 

Uma lista pode conter zero ou mais elementos de um
mesmo tipo ou de tipos diversos, podendo inclusive conter outras listas. 

O tamanho de uma lista é igual à quantidade de elementos que ela contém.

Listas são entidades mutáveis

In [ ]:
# Criando uma lista vazia 

L = []

print(L)

In [ ]:
type(L)

Os colchetes ([ ]) após o símbolo de igualdade servem para indicar que L é uma
lista.

In [ ]:
# Lista com três elementos

Z = [1, 2, 3]

Podemos usar a função **len** com listas. 

O valor retornado é igual ao número de elementos da lista.

Logo, dizemos que o tamanho da lista Z é 3.

In [ ]:
len(Z)

In [ ]:
type(Z)

Lista com elementos do tipo string

In [ ]:
lista_escritório = ['caneta', 'caderno', 'mesa', 'borracha']

In [ ]:
len(lista_escritório)

Listas também podem conter tipos diferentes de variáveis

In [ ]:
lista_mista = [1, 'casa', 30, 40.5, 'árvore']
len(lista_mista)

Relembrando operações com índices em string

In [ ]:
rua = 'Av. Getúlio Vargas'

In [ ]:
rua[0]

In [ ]:
rua[10]

In [ ]:
rua[-1]

In [ ]:
rua[0:17]

In [ ]:
rua[5:10]

## Acessando os elementos de uma lista

O acesso aos elementos de uma lista é feito através de um índice, índice cujo a numeração começa do zero.

<img src="https://miro.medium.com/max/1110/1*bsIn4oKr3nDMcmp4JXiQzQ.png" alt="Drawing" style="width: 900px"/>

In [ ]:
lista_python = ['P', 'Y', 'T', 'H', 'O', 'N']

In [ ]:
lista_python[0]

In [ ]:
lista_python[1]

In [ ]:
lista_python[6]

In [ ]:
lista_python[5]

In [ ]:
lista_python[-1]

In [ ]:
lista_python[-3]

In [ ]:
lista_python[-6]

Outra lista

In [ ]:
lista = [0, 2, 4, 6]

In [ ]:
lista[0]

In [ ]:
lista[1]

In [ ]:
lista[-3]

In [ ]:
lista[-1]

In [ ]:
lista[-1] == lista[-3]

In [ ]:
lista[-1] = 'A'

In [ ]:
lista

In [ ]:
lista[1] = lista[-3]

In [ ]:
lista

In [ ]:
lista[1] = lista[-2]

In [ ]:
lista

## Modificação de uma lista

In [ ]:
lista = [0, 2, 4, 6]

In [ ]:
lista[0] = -20

In [ ]:
lista

[-20, 2, 4, 6]

In [ ]:
lista[1] = lista[-2]

In [ ]:
lista

[-20, 4, 4, 6]

## Cópia e fatiamento de listas

Embora listas em Python sejam um recurso muito poderoso, todo poder traz
responsabilidades. Um dos efeitos colaterais de listas aparece quando tentamos
fazer cópias.

Vejamos o código abaixo

In [ ]:
# Tentativa de copiar listas

L = [1,2,3,4,5]

In [ ]:
V = L

In [ ]:
L

[1, 2, 3, 4, 5]

In [ ]:
V

[1, 2, 3, 4, 5]

In [ ]:
V[0] = 6

In [ ]:
V

[6, 2, 3, 4, 5]

In [ ]:
L

[6, 2, 3, 4, 5]

Veja que, ao modificarmos V , modificamos também o conteúdo de L. 

Isso porque uma lista em Python é um objeto e, quando atribuímos um objeto a outro, estamos apenas copiando a mesma referência da lista, e não seus dados em si. 

Nesse caso, V funciona como um apelido de L, ou seja, V e L são a mesma lista.

Dependendo da aplicação, esse efeito pode ser desejado ou não. 

Para criar uma cópia independente de uma lista, utilizaremos outra sintaxe.

In [ ]:
# Cópia de listas

L = [1, 2, 3, 4, 5]

In [ ]:
V = L[:]

In [ ]:
V[0] = 6

In [ ]:
V

[6, 2, 3, 4, 5]

In [ ]:
L

[1, 2, 3, 4, 5]

Ao escrevermos L[:] , estamos nos referindo a uma nova cópia de L . Assim L e V se referem a áreas diferentes na memória, permitindo alterá-las de forma independente.

Podemos também fatiar uma lista, da mesma forma que fizemos com strings.

In [ ]:
# Fatiamento de listas

L = [1, 2, 3, 4, 5]

In [ ]:
L[0:5]

[1, 2, 3, 4, 5]

In [ ]:
L[:-1]

In [ ]:
L[0:-1]

In [ ]:
L[0:]

In [ ]:
L[1:3]

In [ ]:
L[1:4]

In [ ]:
L[3:]

In [ ]:
L[:3]

In [ ]:
L[-1]

In [ ]:
L[-3]

Veja que índices negativos também funcionam. Um índice negativo começa a contar do último elemento, mas observe que começamos de -1 . Assim L[0] representa o primeiro elemento; L[-1], o último; L[-2], o penúltimo, e assim por diante.

## Adição de elementos

Uma das principais vantagens de trabalharmos com listas é poder adicionar novos
elementos durante a execução do programa.

Para adicionar um elemento ao fim da lista, utilizaremos o método **append**. 

Em Python, chamamos um método escrevendo o nome dele após o nome do objeto.
Como listas são objetos, sendo L a lista, teremos L.append(valor). 

Métodos são recursos de orientação a objetos, suportados e muito usados em Python. Você pode imaginar um método como uma função do objeto. Quando invocado, ele já sabe a que objeto estamos nos referindo, pois o informamos à esquerda do ponto.

In [ ]:
# Adição de elementos à lista

L = []

In [ ]:
L.append('a')

In [ ]:
L

['a']

In [ ]:
L.append('b')

In [ ]:
L

['a', 'b']

In [ ]:
L.append('c')

In [ ]:
L

['a', 'b', 'c']

In [ ]:
L.append(1)

In [ ]:
L

['a', 'b', 'c', 1]

In [ ]:
L.append(2.5)

In [ ]:
L

['a', 'b', 'c', 1, 2.5]

In [ ]:
L.append(True)

In [ ]:
L

['a', 'b', 'c', 1, 2.5, True]

Quando adicionamos apenas um elemento, tanto L.append(1) quanto L+[1] produzem
o mesmo resultado. 

Perceba que em L+[1] escrevemos o elemento a adicionar dentro de uma lista ([1]), e que, em append, apenas 1.

Isso porque, quando adicionamos uma lista a outra, o interpretador executa um método chamado **extend** que adiciona os elementos de uma lista a outra.

In [ ]:
# Adição de listas

L = []

In [ ]:
L = L + [1]

In [ ]:
L

[1]

In [ ]:
L = L + [2]

In [ ]:
L

[1, 2]

In [ ]:
L += [3]

In [ ]:
L

[1, 2, 3]

In [ ]:
L += [3,4,5]

In [ ]:
L

[1, 2, 3, 3, 4, 5]

In [ ]:
# Adição de elementos e listas

L = ["a"]

In [ ]:
L.append("b")

In [ ]:
L

['a', 'b']

In [ ]:
L.append(["d","e"])

In [ ]:
L

['a', 'b', ['d', 'e']]

In [ ]:
len(L)

3

Método *extend*

In [ ]:
L = []

In [ ]:
L.extend(["f"])

In [ ]:
L

['f']

In [ ]:
L.extend(["f", "g", "h"])

In [ ]:
L

['f', 'f', 'g', 'h']

In [ ]:
len(L)

4

## Remoção de elementos da lista

Como o tamanho da lista pode variar, permitindo a adição de novos elementos,
podemos também retirar alguns elementos da lista, ou mesmo todos eles. Para
isso, utilizaremos a instrução **del**.

In [ ]:
L = ["a", "b", "c"]

In [ ]:
len(L)

3

In [ ]:
L[2]

'c'

In [ ]:
del L[1]

In [ ]:
L

['a', 'c']

In [ ]:
len(L)

2

In [ ]:
L[2]

IndexError: ignored

In [ ]:
L

['a', 'c']

É importante notar que o elemento excluído não ocupa mais lugar na lista, fazendo com que os índices sejam reorganizados, ou melhor, que passem a ser calculados sem esse elemento.

## Concatenação e multiplicação

Também é possível concatenar listas por meio do operador de adição '+' e multiplicá-las por um inteiro, o que gerará várias cópias dos seus itens. 

O código a seguir traz alguns exemplos dessas operações:



In [ ]:
# Relembrando string

In [ ]:
# concatenação

a = 'casa'
b = ' de praia'
a + b

'casa de praia'

In [ ]:
# multiplicação de strings

c = 'Gol'
d = c * 5
print(d)

GolGolGolGolGol


Para lista: 

In [ ]:
lista_1 = ['O carro azul', 'peixe', 123, 111, 'pedra']

In [ ]:
lista_2 = ['O carro preto', 'galinha', 1233, 1141]

In [ ]:
concat = lista_1 + lista_2
print(concat)

['O carro azul', 'peixe', 123, 111, 'pedra', 'O carro preto', 'galinha', 1233, 1141]


In [ ]:
mult_lista = concat * 3
print(mult_lista)

In [ ]:
mult_lista2 = lista_2 * 3
print(mult_lista2)

['O carro preto', 'galinha', 1233, 1141, 'O carro preto', 'galinha', 1233, 1141, 'O carro preto', 'galinha', 1233, 1141]


In [ ]:
# Lista não é um vetor

a = [1, 3, 5]
b = [2, 4, 6]
c = a + b
print(c)

[1, 3, 5, 2, 4, 6]


In [ ]:
# Lista não é um vetor

a = [1, 3, 5]
b = [2, 4, 6]
c = a * b
print(c)

TypeError: ignored

## Verificando a existência de itens em uma lista

Em alguns casos é preciso verificar se um determinado valor está contido em uma lista. 

Para isso, em Python utilizamos o operador **in**, que indicará True se objeto pertencer ao conjunto, e False caso contrário. 

No código a seguir temos exemplos de uso desse operador:

In [ ]:
lista = ['O carro azul', 'peixe', 123, 111, 'pedra']

In [ ]:
'peixe' in lista

True

In [ ]:
'peixe' not in lista

False

In [ ]:
'gato' in lista

False

In [ ]:
'gato' not in lista

True

Mais sobre listas:

https://www.devmedia.com.br/como-trabalhar-com-listas-em-python/37460

https://docs.python.org/pt-br/3/tutorial/datastructures.html#

## Range

Podemos utilizar a função range para gerar listas simples. A função range não retorna uma lista propriamente dita, mas um gerador ou generator. 

Por enquanto, basta entender como podemos usá-la. Imagine um programa simples que imprime de 0 a 9 na tela:

In [ ]:
# Criando uma lista

L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
a = range(10)
type(a)

range

In [ ]:
a

range(0, 10)

In [ ]:
a = list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Obter ajuda para determinada função:

`nome_da_função?`

In [ ]:
range?

In [ ]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

A vantagem de utilizarmos a função range é gerar listas eficientemente.

In [ ]:
# Transformação do resultado de range em uma lista

L = list(range(100, 1100, 50))
print(L)

[100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050]


# Tuplas

Uma tupla é uma coleção de objetos que lembra muito as listas, com a grande diferença de serem **imutáveis**. Tuplas são ideais para representar listas de valores constantes e também para realizar operações de empacotamento e desempacotamento de valores.

Tuplas são criadas de forma semelhante às listas, mas utilizamos **parênteses** em vez de colchetes. Por exemplo:

In [ ]:
# criação de uma tupla

tupla = ("a", "b", "c")
print(tupla)

('a', 'b', 'c')


In [ ]:
type(tupla)

tuple

In [ ]:
type?

In [ ]:
# criação de outra tupla

outra_tupla = ("a", 1, 1.5, [1, 2], True)
print(outra_tupla)

('a', 1, 1.5, [1, 2], True)


Tuplas suportam a maior parte das operações de lista, como fatiamento e indexação.

In [ ]:
tupla[0]

'a'

In [ ]:
tupla[2]

'c'

In [ ]:
tupla[1:]

('b', 'c')

In [ ]:
tupla.append('a')

AttributeError: ignored

In [ ]:
del tupla[0]

TypeError: ignored

In [ ]:
tupla

('a', 'b', 'c')

In [ ]:
len(tupla)

3

In [ ]:
tupla = tupla + tupla + tupla

In [ ]:
tupla

('a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c')

In [ ]:
len(tupla)

9

Mas tuplas não podem ter seus elementos alterados. Veja o que acontece se tentarmos alterar uma tupla:

In [ ]:
tupla[0] = "A"

TypeError: ignored

Python também permite criar tuplas usando valores separados por vírgula, independente de usarmos parênteses:

In [ ]:
tupla = 100, 200, 300

In [ ]:
print(tupla)

(100, 200, 300)


In [ ]:
type(tupla)

tuple

No caso, 100, 200 e 300 foram convertidos em uma tupla com três elementos. Esse
tipo de operação é chamado de **empacotamento**.

Tuplas também podem ser utilizadas para desempacotar valores, por exemplo:

In [ ]:
empacotar = 1, 2, 3, 4, 6, 7, 8

In [ ]:
print(empacotar)

(1, 2, 3, 4, 6, 7, 8)


Para desempacotar:

In [ ]:
a, b, c = 10, 20, 30

In [ ]:
a

10

In [ ]:
b

20

In [ ]:
c

30

Planilha contém valores de ações em função: Col1 (tempo), Col2 (Ação 1), Col3 (Ação 2), ...

t, acao_1, acao_2 = ABRE_ARQUIVO(Planilha)

plotar(t, acao_1)

Devemos acrescentar uma vírgula para indicar que o valor é uma tupla com apenas um elemento:

In [ ]:
t0 = 1

In [ ]:
type(t0)

int

In [ ]:
t1 = (1)

In [ ]:
print(t1)

1


In [ ]:
type(t1)

int

In [ ]:
t2 = (1,)

In [ ]:
print(t2)

(1,)


In [ ]:
type(t2)

tuple

In [ ]:
t3 = 1,

In [ ]:
print(t3)

(1,)


In [ ]:
type(t3)

tuple

Podemos também criar tuplas vazias, escrevendo apenas os parênteses:

In [ ]:
t4 = ()

In [ ]:
len(t4)

In [ ]:
type(t4)

Tuplas também podem ser criadas a partir de listas, utilizando-se a função tuple:

In [ ]:
tuple?

In [ ]:
L = [1,2,3]
T = tuple(L)

In [ ]:
print(L)

[1, 2, 3]


In [ ]:
print(T)

(1, 2, 3)


In [ ]:
W = list(T)
print(W)

[1, 2, 3]


Embora não possamos alterar uma tupla depois de sua criação, podemos concatená-las, gerando novas tuplas:

In [ ]:
t1 = (1,2,3)
t2 = (4,5,6)

In [ ]:
t3 = t1+t2
t3

(1, 2, 3, 4, 5, 6)

Observe que se uma tupla contiver uma lista ou outro objeto que pode ser alterado, este continuará a funcionar normalmente. Veja o exemplo de uma tupla
que contém uma lista:

In [ ]:
tupla = ("a", ["b", "c", "d"])

In [ ]:
tupla

('a', ['b', 'c', 'd'])

In [ ]:
len(tupla)

2

In [ ]:
tupla[1]

['b', 'c', 'd']

In [ ]:
tupla[1].append("e")

In [ ]:
tupla

('a', ['b', 'c', 'd', 'e'])

In [ ]:
len(tupla)

2

Neste caso, nada mudou na tupla em si, mas na lista que é seu segundo elemento.
Ou seja, a tupla não foi alterada, mas a lista que ela continha, sim.

# Dicionários

Um dicionário é uma coleção, assim como as listas e as tuplas. 

Porém, enquanto as tuplas eram indexadas por um índice, os dicionários são indexados por chaves. Todo elemento em um dicionário possui uma chave e um valor. 

Chaves tipicamente são strings, valores podem ser qualquer tipo de dado.

O dicionário em si consiste em relacionar uma chave a um valor específico.

Em Python, criamos dicionários utilizando chaves (**{}**). Cada elemento do dicionário é uma combinação de chave e valor.

Vejamos como criar esse dicionário em Python:


|  Produto  |  Preço (kg) |
|:---------:|:-----------:|
|   Alface  | R\$ 0,99    |
|   Tomate  | R\$ 3,99    |  
|    Maçã   | R\$ 4,49    |
| Tangerina | R\$ 2,99    |

In [ ]:
tabela = {"Alface": 0.99, "Tomate": 3.99, "Maçã": 4.49, "Tangerina": 2.99}

In [ ]:
tabela

{'Alface': 0.99, 'Maçã': 4.49, 'Tangerina': 2.99, 'Tomate': 3.99}

In [ ]:
tabela = {"Alface": 0.99,
          "Tomate": 3.99,
          "Maçã": 4.49,
          "Tangerina": 2.99}

In [ ]:
tabela

{'Alface': 0.99, 'Maçã': 4.49, 'Tangerina': 2.99, 'Tomate': 3.99}

In [ ]:
type(tabela)

dict

In [ ]:
print(tabela)

{'Alface': 0.99, 'Tomate': 3.99, 'Maçã': 4.49, 'Tangerina': 2.99}


In [ ]:
len(tabela)

4

In [ ]:
print(tabela["Alface"])

0.99


In [ ]:
tabela2 = {"Alface": 0.99, "Tomate": 3.99, "Maçã": 4.49, "Tangerina": 2.99, "Pera": 5.99}

In [ ]:
print(tabela2)

{'Alface': 0.99, 'Tomate': 3.99, 'Maçã': 4.49, 'Tangerina': 2.99, 'Pera': 5.99}


Um dicionário é acessado por suas chaves. Para obter o preço da alface, digite
no interpretador, depois de ter criado a tabela, tabela["Alface"] , onde tabela é o nome da variável do tipo dicionário, e “Alface” é nossa chave. O valor retornado é o mesmo que associamos na tabela, ou seja, R\$ 0,99.

In [ ]:
tabela["Alface"]

0.99

In [ ]:
tabela["Maçã"]

4.49

In [ ]:
tabela['Tangerina']

2.99

In [ ]:
tabela[0]

KeyError: ignored

In [ ]:
L = [1, 2, 3]

In [ ]:
L = L + [4]

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
L[0] = 0

In [ ]:
L

[0, 2, 3, 4]

Diferentemente de listas, onde o índice é um número, dicionários utilizam suas
chaves como índice. 

Quando atribuímos um valor a uma chave, duas coisas podem ocorrer:

1. Se a chave já existe: o valor associado é alterado para o novo valor.
2. Se a chave não existe: a nova chave será adicionada ao dicionário.

In [ ]:
# Funcionamento do dicionário

tabela = {"Alface": 0.99,
          "Tomate": 3.99,
          "Maçã": 4.49,
          "Tangerina": 2.99}

In [ ]:
print(tabela["Tomate"])

3.99


In [ ]:
print(tabela)

{'Alface': 0.99, 'Tomate': 3.99, 'Maçã': 4.49, 'Tangerina': 2.99}


In [ ]:
tabela["Tomate"] = 5.99

In [ ]:
print(tabela["Tomate"])

5.99


In [ ]:
tabela["Cebola"]

KeyError: ignored

In [ ]:
tabela["Cebola"] = 2.29

In [ ]:
print(tabela)

{'Alface': 0.99, 'Tomate': 5.99, 'Maçã': 4.49, 'Tangerina': 2.99, 'Cebola': 2.29}


Para verificar se uma chave existe: 

In [ ]:
# Acessando uma chave inexistente

tabela = {"Alface": 0.99,
          "Tomate": 3.99,
          "Maçã": 4.49,
          "Tangerina": 2.99}

In [ ]:
print(tabela["Manga"])

KeyError: ignored

Se a chave não existir, uma exceção do tipo KeyError será ativada. Para verificar se uma chave pertence ao dicionário, podemos usar o operador **in**:

In [ ]:
# Verificação da existência de uma chave

tabela = {"Alface": 0.99,
          "Tomate": 3.99,
          "Maçã": 4.49,
          "Tangerina": 2.99}

In [ ]:
print("Manga" in tabela)

False


In [ ]:
print("Maçã" in tabela)

True


Podemos também obter uma lista com as chaves do dicionário, ou mesmo uma lista dos valores associados:

In [ ]:
# Obtenção de uma lista de chaves e valores

tabela = {"Alface": 0.99,
          "Tomate": 3.99,
          "Maçã": 4.49,
          "Tangerina": 2.99}

In [ ]:
print(tabela.keys())

dict_keys(['Alface', 'Tomate', 'Maçã', 'Tangerina'])


In [ ]:
print(tabela.values())

dict_values([0.99, 3.99, 4.49, 2.99])


Criando um dicionário (maneira alternativa)

In [ ]:
# Claudio

tabela = dict()

tabela['Alface'] = 0.99
tabela['Tomate'] = 3.99

print(tabela) 

{'Alface': 0.99, 'Tomate': 3.99}


Para apagar uma chave, utilizaremos a instrução **del**:

In [ ]:
# Exclusão de uma associação do dicionário

tabela = {"Alface": 0.99,
          "Tomate": 3.99,
          "Maçã": 4.49,
          "Tangerina": 2.99}

In [ ]:
del tabela["Tomate"]

In [ ]:
print(tabela)

{'Alface': 0.99, 'Maçã': 4.49, 'Tangerina': 2.99}


Quando utilizar dicionário:

* Se seus dados são facilmente acessados por suas chaves, quase nunca você precisa acessá-los de uma só vez
* Você pode acessar os valores associados a uma chave rapidamente sem pesquisar

## Dicionários com listas

Em Python, podemos ter dicionários nos quais as chaves são associadas a listas
ou mesmo a outros dicionários.

Imagine uma relação de estoque de mercadorias onde teríamos, além do preço, a quantidade em estoque:



In [ ]:
# Dicionário com listas

estoque = {"Alface": [500, 0.99],
          "Tomate": [2000, 3.99],
          "Maçã": [1500, 4.49],
          "Tangerina": [600, 2.99]}

Nesse caso, o nome do produto é a chave, e a lista consiste nos valores associados, uma lista por chave. O primeiro elemento da lista é a quantidade disponível; e o segundo, o preço do produto.

Uma aplicação seria processarmos uma lista de operações e calcular o preço total
de venda, atualizando também a quantidade em estoque:



In [ ]:
estoque = {"Alface": [500, 0.99],
          "Tomate": [2000, 3.99],
          "Maçã": [1500, 4.49],
          "Tangerina": [600, 2.99]}

estoque.items()

dict_items([('Alface', [500, 0.99]), ('Tomate', [2000, 3.99]), ('Maçã', [1500, 4.49]), ('Tangerina', [600, 2.99])])

**Método de dicionários get()**

O método **get()** retorna o valor da chave especificada se a chave existir no dicionário.

Sintaxe: 

```
dict.get(chave[, valor]) 
```
* chave - chave a ser pesquisada no dicionário.  
* valor (opcional) - valor a ser devolvido se a chave não for encontrada. O valor padrão é `None`.


In [ ]:
dicionário = {"Alface": 0.99,
              "Tomate": 3.99,
              "Maçã": 4.49,
              "Tangerina": 2.99}

In [ ]:
print(dicionário.get("Alface"))

0.99


In [ ]:
print(dicionário.get("Laranja"))

None


In [ ]:
type(None)

In [ ]:
print(dicionário.get("Laranja"), 0)

None 0


In [ ]:
print(dicionário.get("Laranja"), 10)

None 10


# Vetores e matrizes


## Vetores


 
Um vetor é uma sequência de dados ocupando posições consecutivas de memória e por isso existe uma ordem natural (o primeiro elemento, o segundo e assim por diante). 

A grande vantagem de usar vetor é poder trabalhar com um grande número de variáveis utilizando um único nome (para a variável). Para isso existe uma sintaxe especial para pegar elementos do vetor em posições específicas (como o primeiro elemento ou o décimo elemento).

Em Python, o termo **lista** é comumente usado quando queremos nos referir a vetores, mas embarca um conceito mais amplo, uma vez que listas podem conter elementos de tipos diferentes, podendo inclusive incluir outras listas.





Vetor é uma quantidade que possui direção, magnetitude (intensidade) e sentido. 

<img src="https://linuxhint.com/wp-content/uploads/2019/06/1-34.png"/>

Vetores são muito importantes em **Machine Learning**, pois eles não apenas descrevem a magnitude, mas também a direção das features.

Em Python, podemos entender um vetor como um array unidimensional.

NumPy: https://numpy.org/doc/stable/user/absolute_beginners.html



In [ ]:
# Para definir um vetor em Python, temos que usar a biblioteca numpy (que inclui função array)

import numpy as np

lista = [1,2,3]

vetor_linha = np.array(lista)

print(vetor_linha)

[1 2 3]


In [ ]:
type(lista)

list

In [ ]:
type(vetor_linha)

numpy.ndarray

In [ ]:
vetor_coluna = [[1],[2],[3]]
vetor_coluna = np.array(vetor_coluna)
print(vetor_coluna)

[[1]
 [2]
 [3]]


Operações básicas com vetores em Python:

* Adição
* Subtração
* Multiplicação
* Divisão
* Produto interno, etc

In [ ]:
# Adição

import numpy as np 
 
lst1 = [10, 20, 30, 40, 50] 
lst2 = [1, 2, 3, 4, 5]
 
 
vctr1 = np.array(lst1) 
 
vctr2 = np.array(lst2) 
 
 
print("Vetor criado a partir da lista 1:") 
print(vctr1) 
print("Vetor criado a partir da lista 2:") 
print(vctr2) 

Vetor criado a partir da lista 1:
[10 20 30 40 50]
Vetor criado a partir da lista 2:
[1 2 3 4 5]


In [ ]:
type(vctr1)

numpy.ndarray

In [ ]:
vctr_add = vctr1 + vctr2
print("Adição de dois vetores: ",vctr_add)

Adição de dois vetores:  [11 22 33 44 55]


In [ ]:
vctr_produto = vctr1 * vctr2
print("Produto de dois vetores: ", vctr_produto)

Produto de dois vetores:  [ 10  40  90 160 250]


In [ ]:
vctr_div = vctr1 / vctr2
print("Produto de dois vetores: ", vctr_div)

Produto de dois vetores:  [10. 10. 10. 10. 10.]


In [ ]:
vctr1[-1]

50

In [ ]:
vctr1[0]

10

In [ ]:
vctr1[0:3]

array([10, 20, 30])

## Matrizes

Uma matriz é uma estrutura de dados onde números estão arranjados em linhas e colunas. Uma matriz é uma matriz 3X4 (três por quatro) porque ele possui 3 linhas e 4 colunas.

Em Python não há uma construção embutida para matrizes. Porém, podemos tratar uma lista de uma lista como uma matriz. Por exemplo:

In [ ]:
A = [[1, 4, 5], 
    [-5, 8, 9]]

In [ ]:
A

[[1, 4, 5], [-5, 8, 9]]

In [ ]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

In [ ]:
print("A =", A) 

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]


In [ ]:
print("A[1] =", A[1])      # segunda linha

A[1] = [-5, 8, 9, 0]


In [ ]:
print("A[1][2] =", A[1][2])   # terceiro elemento da segunda linha

A[1][2] = 9


In [ ]:
print("A[0][-1] =", A[0][-1])   # Último elemento da primeira linha

A[0][-1] = 12


Usar listas aninhadas (lista de listas) como uma matriz funciona para tarefas simples, porém, há uma maneira melhor de trabalhar com matrizes em Python usando o pacote Numpy.